name: Generate Static Site

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - working-directory: ./github-profile-finder
              name: github-profile-finder build
              run: |
                  yarn install
                  yarn build
                  touch build/.nojekyll
                  mkdir -p ../gh-pages/github-profile-finder
                  cp ./build/* ../gh-pages/github-profile-finder
            - working-directory: ./d-day-calc
              name: d-day-calc build
              run: |
                  yarn install
                  yarn build
                  touch build/.nojekyll
                  mkdir -p ../gh-pages/d-day-calc
                  cp ./build/* ../gh-pages/d-day-calc
                  
            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: gh-pages
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
